# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106263a175e1da25130ebe8187876b97300e8a58f580dce958355e6b41763dd05c6a8bb3d228223188f2b302bfc92fd9b8fac4c87657ae32ffdff876a922ef98

test:
  secret_key_base: 4ebe26ead3c745966a3410c01b5b7f07fee30f3e6c6170599ee17ae02c5d9e3ad7944888c590dd457de7a22e32fdce7366fc0726b31324abaada6465bfaa161b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
